/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardLayoutImport } from './routes/dashboard/layout'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as DashboardNiceImport } from './routes/dashboard/nice'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as DashboardTenantsIndexImport } from './routes/dashboard/tenants/index'
import { Route as DashboardShopsIndexImport } from './routes/dashboard/shops/index'
import { Route as DashboardPaymentsIndexImport } from './routes/dashboard/payments/index'
import { Route as DashboardBillsIndexImport } from './routes/dashboard/bills/index'
import { Route as DashboardBillsPrintImport } from './routes/dashboard/bills/print'
import { Route as DashboardTenantsTenantIndexImport } from './routes/dashboard/tenants/$tenant/index'
import { Route as DashboardShopsShopIndexImport } from './routes/dashboard/shops/$shop/index'

// Create/Update Routes

const DashboardLayoutRoute = DashboardLayoutImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardNiceRoute = DashboardNiceImport.update({
  path: '/nice',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const DashboardTenantsIndexRoute = DashboardTenantsIndexImport.update({
  path: '/tenants/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardShopsIndexRoute = DashboardShopsIndexImport.update({
  path: '/shops/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardPaymentsIndexRoute = DashboardPaymentsIndexImport.update({
  path: '/payments/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardBillsIndexRoute = DashboardBillsIndexImport.update({
  path: '/bills/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardBillsPrintRoute = DashboardBillsPrintImport.update({
  path: '/bills/print',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardTenantsTenantIndexRoute =
  DashboardTenantsTenantIndexImport.update({
    path: '/tenants/$tenant/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardShopsShopIndexRoute = DashboardShopsShopIndexImport.update({
  path: '/shops/$shop/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/nice': {
      id: '/dashboard/nice'
      path: '/nice'
      fullPath: '/dashboard/nice'
      preLoaderRoute: typeof DashboardNiceImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/bills/print': {
      id: '/dashboard/bills/print'
      path: '/bills/print'
      fullPath: '/dashboard/bills/print'
      preLoaderRoute: typeof DashboardBillsPrintImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/bills/': {
      id: '/dashboard/bills/'
      path: '/bills'
      fullPath: '/dashboard/bills'
      preLoaderRoute: typeof DashboardBillsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/payments/': {
      id: '/dashboard/payments/'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/shops/': {
      id: '/dashboard/shops/'
      path: '/shops'
      fullPath: '/dashboard/shops'
      preLoaderRoute: typeof DashboardShopsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/tenants/': {
      id: '/dashboard/tenants/'
      path: '/tenants'
      fullPath: '/dashboard/tenants'
      preLoaderRoute: typeof DashboardTenantsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/shops/$shop/': {
      id: '/dashboard/shops/$shop/'
      path: '/shops/$shop'
      fullPath: '/dashboard/shops/$shop'
      preLoaderRoute: typeof DashboardShopsShopIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/tenants/$tenant/': {
      id: '/dashboard/tenants/$tenant/'
      path: '/tenants/$tenant'
      fullPath: '/dashboard/tenants/$tenant'
      preLoaderRoute: typeof DashboardTenantsTenantIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface DashboardLayoutRouteChildren {
  DashboardNiceRoute: typeof DashboardNiceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBillsPrintRoute: typeof DashboardBillsPrintRoute
  DashboardBillsIndexRoute: typeof DashboardBillsIndexRoute
  DashboardPaymentsIndexRoute: typeof DashboardPaymentsIndexRoute
  DashboardShopsIndexRoute: typeof DashboardShopsIndexRoute
  DashboardTenantsIndexRoute: typeof DashboardTenantsIndexRoute
  DashboardShopsShopIndexRoute: typeof DashboardShopsShopIndexRoute
  DashboardTenantsTenantIndexRoute: typeof DashboardTenantsTenantIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardNiceRoute: DashboardNiceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBillsPrintRoute: DashboardBillsPrintRoute,
  DashboardBillsIndexRoute: DashboardBillsIndexRoute,
  DashboardPaymentsIndexRoute: DashboardPaymentsIndexRoute,
  DashboardShopsIndexRoute: DashboardShopsIndexRoute,
  DashboardTenantsIndexRoute: DashboardTenantsIndexRoute,
  DashboardShopsShopIndexRoute: DashboardShopsShopIndexRoute,
  DashboardTenantsTenantIndexRoute: DashboardTenantsTenantIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/nice': typeof DashboardNiceRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/bills/print': typeof DashboardBillsPrintRoute
  '/dashboard/bills': typeof DashboardBillsIndexRoute
  '/dashboard/payments': typeof DashboardPaymentsIndexRoute
  '/dashboard/shops': typeof DashboardShopsIndexRoute
  '/dashboard/tenants': typeof DashboardTenantsIndexRoute
  '/dashboard/shops/$shop': typeof DashboardShopsShopIndexRoute
  '/dashboard/tenants/$tenant': typeof DashboardTenantsTenantIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/nice': typeof DashboardNiceRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/bills/print': typeof DashboardBillsPrintRoute
  '/dashboard/bills': typeof DashboardBillsIndexRoute
  '/dashboard/payments': typeof DashboardPaymentsIndexRoute
  '/dashboard/shops': typeof DashboardShopsIndexRoute
  '/dashboard/tenants': typeof DashboardTenantsIndexRoute
  '/dashboard/shops/$shop': typeof DashboardShopsShopIndexRoute
  '/dashboard/tenants/$tenant': typeof DashboardTenantsTenantIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/nice': typeof DashboardNiceRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/dashboard/bills/print': typeof DashboardBillsPrintRoute
  '/dashboard/bills/': typeof DashboardBillsIndexRoute
  '/dashboard/payments/': typeof DashboardPaymentsIndexRoute
  '/dashboard/shops/': typeof DashboardShopsIndexRoute
  '/dashboard/tenants/': typeof DashboardTenantsIndexRoute
  '/dashboard/shops/$shop/': typeof DashboardShopsShopIndexRoute
  '/dashboard/tenants/$tenant/': typeof DashboardTenantsTenantIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/signup'
    | '/dashboard/nice'
    | '/auth'
    | '/dashboard/'
    | '/profile'
    | '/dashboard/bills/print'
    | '/dashboard/bills'
    | '/dashboard/payments'
    | '/dashboard/shops'
    | '/dashboard/tenants'
    | '/dashboard/shops/$shop'
    | '/dashboard/tenants/$tenant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signup'
    | '/dashboard/nice'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/dashboard/bills/print'
    | '/dashboard/bills'
    | '/dashboard/payments'
    | '/dashboard/shops'
    | '/dashboard/tenants'
    | '/dashboard/shops/$shop'
    | '/dashboard/tenants/$tenant'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/signup'
    | '/dashboard/nice'
    | '/auth/'
    | '/dashboard/'
    | '/profile/'
    | '/dashboard/bills/print'
    | '/dashboard/bills/'
    | '/dashboard/payments/'
    | '/dashboard/shops/'
    | '/dashboard/tenants/'
    | '/dashboard/shops/$shop/'
    | '/dashboard/tenants/$tenant/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/auth/signup",
        "/auth/",
        "/profile/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/layout.tsx",
      "children": [
        "/dashboard/nice",
        "/dashboard/",
        "/dashboard/bills/print",
        "/dashboard/bills/",
        "/dashboard/payments/",
        "/dashboard/shops/",
        "/dashboard/tenants/",
        "/dashboard/shops/$shop/",
        "/dashboard/tenants/$tenant/"
      ]
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/dashboard/nice": {
      "filePath": "dashboard/nice.tsx",
      "parent": "/dashboard"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/dashboard/bills/print": {
      "filePath": "dashboard/bills/print.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/bills/": {
      "filePath": "dashboard/bills/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/payments/": {
      "filePath": "dashboard/payments/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/shops/": {
      "filePath": "dashboard/shops/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/tenants/": {
      "filePath": "dashboard/tenants/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/shops/$shop/": {
      "filePath": "dashboard/shops/$shop/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/tenants/$tenant/": {
      "filePath": "dashboard/tenants/$tenant/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
